# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: '179593885'

menu:
- {name: 'Microbial', folder: 'pages', file: 'microbial.html'}
- {name: 'Transcriptomic', folder: 'pages', file: 'rnaseq.html'}
- {name: 'Human Genetics', folder: 'pages', file: 'genes.html'}
- {name: 'Misc', folder: 'pages', file: 'misc.html'}
- {name: 'Publications', folder: 'pages', file: 'pubs.html'}
- {name: 'About', folder: 'pages', file: 'about.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/rrbiiiphd'}
# - {icon: 'facebook', link: 'https://www.facebook.com/Le.Paul.94'}
# - {icon: 'instagram', link: 'https://instagram.com/paululele'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/robert-butler-3111a457/'}
- {icon: 'envelope', link: 'mailto:rrbutleriii@gmail.com'}
- {icon: 'github', link: 'https://github.com/rbutleriii'}
- {icon: 'google', link: 'https://scholar.google.com/citations?user=JUSoLFkAAAAJ&hl=en'}
# - {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
